image: docker

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

before_script:
  - cd robot/cpp-robot-service-template
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

test:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  stage: test
  script:
    - cd build
    - make
    - make test

build-amd64:
  stage: build
  needs:
    - test
  script:
    - docker build .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

release:
  stage: deploy
  needs:
    - build-amd64
  script:
    - docker build -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" --push .
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9.]+$/
