image: docker

services:
  - docker:dind

stages:
  - scan
  - trigger

scan:
  stage: scan
  script: "echo 'scanning...'"

include:
  - local: "templates/trigger.yml"
    inputs:
      service_name: "docs"
      service_root: "docs"
