image: docker

services:
  - docker:dind

stages:
  - scan
  - trigger

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - local: "templates/trigger.yml"
    inputs:
      service_name: "ansible"
      service_root: "ansible"
  - local: "templates/trigger.yml"
    inputs:
      service_name: "docs"
      service_root: "docs"
  - local: "templates/trigger.yml"
    inputs:
      service_name: "robot-perception-service"
      service_root: "robot-perception-service"
  - local: "templates/trigger.yml"
    inputs:
      service_name: "robot-service-template"
      service_root: "robot-service-template"
  - local: "templates/trigger.yml"
    inputs:
      service_name: "web-service-template"
      service_root: "web-service-template"

# override secret detection so stage is "scan"
secret_detection:
  stage: scan
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"
  allow_failure: false
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json
    # this is the way to make artifacts appear
    paths:
      - gl-secret-detection-report.json
    expire_in: 1 day
