stages:
  - scan
  - trigger

variables:
  SECURE_ANALYZERS_PREFIX: "$CI_TEMPLATE_REGISTRY_HOST/security-products"
  SECRET_DETECTION_IMAGE_SUFFIX: ""
  SECRETS_ANALYZER_VERSION: "5"
  SECRET_DETECTION_EXCLUDED_PATHS: ""

  SERVICE_NAME: ""
  SERVICE_DIRECTORY: ""
  SERVICE_TAG_PREFIX: ""

# base job to be extended by downstream pipelines
.base-job:
  needs: ["flag-leaked-secrets"]
  stage: trigger
  trigger:
    include: "$SERVICE_DIRECTORY/.*-ci.yml"
  rules:
    # triggers a downstream pipeline if >=1 conditions are met of::
    #
    #   1. A new tag is created
    #   2. A merge request is made with changes for a service
    #   3. A push to main is made with changes for a service
    #
    - if: '$CI_COMMIT_TAG =~ "$SERVICE_TAG_PREFIX-v*"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $SERVICE_DIRECTORY/**
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - $SERVICE_DIRECTORY/**

flag-leaked-secrets:
  stage: scan
  image: "$SECURE_ANALYZERS_PREFIX/secrets:$SECRETS_ANALYZER_VERSION$SECRET_DETECTION_IMAGE_SUFFIX"
  services: []
  allow_failure: false
  variables:
    GIT_DEPTH: "50"
  # `rules` must be overridden explicitly by each child job
  # see https://gitlab.com/gitlab-org/gitlab/-/issues/218444
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH
  script:
    - /analyzer run

docs:
  extends: .base-job
  variables:
    SERVICE_NAME: "docs"

ansible:
  extends: .base-job
  variables:
    SERVICE_NAME: "ansible"

robot-service-template:
  extends: .base-job
  variables:
    SERVICE_NAME: "robot-service-template"

web-service-template:
  extends: .base-job
  variables:
    SERVICE_NAME: "web-service-template"

robot-perception-service:
  extends: .base-job
  variables:
    SERVICE_NAME: "perception"
