# delegates to child .yml specified ci jobs
# trigger
stages:
  - pre
  - triggers

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml

secret_detection:
  stage: pre

docs-trigger:
  stage: triggers
  trigger:
    include: docs/.docs-ci.yml
  rules:
    - changes:
        - docs/*

infra-trigger:
  stage: triggers
  trigger:
    include: infra/.infra-ci.yml
  rules:
    - changes:
        - infra/*

robot-trigger:
  stage: triggers
  trigger:
    include: robot/.robot-ci.yml
  rules:
    - changes:
        - robot/*

platform-trigger:
  stage: triggers
  trigger:
    include: cloud/.cloud-ci.yml
  rules:
    - changes:
        - cloud/*
