stages:
  - test"
  - trigger
  - release

include:
  - component: "git.chalmers.se/erhaka/team11-project-monorepo/templates/trigger@~latest"
    inputs:
      service_name: "docs"
      service_root: "docs"
  - component: "templates/trigger"
    inputs:
      service_name: "ansible"
      service_root: "ansible"
  - component: "templates/trigger"
    inputs:
      service_name: "web-service-template"
      service_root: "web-service-template"
  - component: "templates/trigger"
    inputs:
      service_name: "robot-service-template"
      service_root: "robot-service-template"
  - component: "templates/trigger"
    inputs:
      service_name: "robot-perception-service"
      service_root: "robot-perception-service"

# components don't get published unless a release job is called...
release:
  stage: release
  script:
    - "echo this supposedly activates components..."
