stages:
  - scan
  - trigger

# base pipe triggers on every change everywhere
# We to override this on a case by case basis
variables:
  RULES_CHANGES_PATH: "**/*"

  SECURE_ANALYZERS_PREFIX: "$CI_TEMPLATE_REGISTRY_HOST/security-products"
  SECRET_DETECTION_IMAGE_SUFFIX: ""

  SECRETS_ANALYZER_VERSION: "5"
  SECRET_DETECTION_EXCLUDED_PATHS: ""

.base-rules:
  rules:
    # always run for main
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    # avoid creation of duplicate jobs for pushing to PR
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    # only way of getting proper handling of glob paths
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $RULES_CHANGES_PATH
    - when: manual
      allow_failure: true

flag-leaked-secrets:
  stage: scan
  image: "$SECURE_ANALYZERS_PREFIX/secrets:$SECRETS_ANALYZER_VERSION$SECRET_DETECTION_IMAGE_SUFFIX"
  services: []
  allow_failure: false
  variables:
    GIT_DEPTH: "50"
  # `rules` must be overridden explicitly by each child job
  # see https://gitlab.com/gitlab-org/gitlab/-/issues/218444
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json

  tags:
    - docker
  extends: .secret-scan-rules
  rules:
    - if: $CI_COMMIT_BRANCH
  script:
    - /analyzer run

docs:
  extends: .base-rules
  stage: trigger
  trigger:
    include: "docs/.docs-ci.yml"
  variables:
    RULES_CHANGES_PATH: "docs/**"

ansible:
  stage: trigger
  extends: .base-rules
  trigger:
    include: "ansible/.ansible-ci.yml"
  variables:
    RULES_CHANGES_PATH: "ansible/**"

robot-service-template:
  stage: trigger
  extends: .base-rules
  trigger:
    include: "robot-service-template/.robot-service-ci.yml"
  variables:
    RULES_CHANGES_PATH: "robot-service-template/**"

web-service-template:
  stage: trigger
  extends: .base-rules
  trigger:
    include: "web-service-template/.web-service-ci.yml"
  variables:
    RULES_CHANGES_PATH: "web-service-template/**"

robot-perception-service:
  extends: .base-rules
  stage: trigger
  trigger:
    include: "perception/.perception-ci.yml"
  variables:
    RULES_CHANGES_PATH: "perception/**"
