stages:
  - scan
  - trigger

variables:
  SECURE_ANALYZERS_PREFIX: "$CI_TEMPLATE_REGISTRY_HOST/security-products"
  SECRET_DETECTION_IMAGE_SUFFIX: ""
  SECRETS_ANALYZER_VERSION: "5"
  SECRET_DETECTION_EXCLUDED_PATHS: ""

  SERVICE_NAME: ""
  SERVICE_DIRECTORY: ""
  SERVICE_TAG_PREFIX: ""

# snippet that avoids doubled pipelines when creating PRs
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - when: always

# base job to be extended by downstream pipelines
.base:
  variables: SERVICE_TAG_PATTERN = '/^$SERVICE_TAG_PREFIX-.*/'
  rules:
    # trigger if changes are found in child directory
    - changes:
        - "$SERVICE_DIRECTORY/**/*"
    # trigger if a tag is created for child service
    # Note that the interpolation cannot be done directly in regex (gitlab bug feature)
    - if: "$CI_COMMIT_TAG =~ $SERVICE_TAG_PATTERN"

  needs: ["flag-leaked-secrets"]
  stage: trigger
  trigger:
    include: "$SERVICE_DIRECTORY/.*-ci.yml"

flag-leaked-secrets:
  stage: scan
  image: "$SECURE_ANALYZERS_PREFIX/secrets:$SECRETS_ANALYZER_VERSION$SECRET_DETECTION_IMAGE_SUFFIX"
  services: []
  allow_failure: false
  variables:
    GIT_DEPTH: "50"
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json
  tags:
    - docker
  script:
    - /analyzer run

docs:
  variables:
    SERVICE_NAME: "docs"
    SERVICE_DIRECTORY: $SERVICE_NAME
    SERVICE_TAG_PREFIX: $SERVICE_NAME
  extends: .base

ansible:
  variables:
    SERVICE_NAME: "ansible"
    SERVICE_DIRECTORY: $SERVICE_NAME
    SERVICE_TAG_PREFIX: $SERVICE_NAME
  extends: .base

robot-service-template:
  variables:
    SERVICE_NAME: "robot-service-template"
    SERVICE_DIRECTORY: $SERVICE_NAME
    SERVICE_TAG_PREFIX: $SERVICE_NAME
  extends: .base

web-service-template:
  variables:
    SERVICE_NAME: "web-service-template"
    SERVICE_DIRECTORY: $SERVICE_NAME
    SERVICE_TAG_PREFIX: $SERVICE_NAME
  extends: .base

robot-perception-service:
  variables:
    SERVICE_NAME: "perception"
    SERVICE_DIRECTORY: $SERVICE_NAME
    SERVICE_TAG_PREFIX: $SERVICE_NAME
  extends: .base
