stages:
  - scan
  - build

# base pipe triggers on every change everywhere
# We to override this on a case by case basis
variables:
  RULES_CHANGES_PATH: "**/*"

  SECURE_ANALYZERS_PREFIX: "$CI_TEMPLATE_REGISTRY_HOST/security-products"
  SECRET_DETECTION_IMAGE_SUFFIX: ""

  SECRETS_ANALYZER_VERSION: "5"
  SECRET_DETECTION_EXCLUDED_PATHS: ""

.base-rules:
  rules:
    # always run for main
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    # avoid creation of duplicate jobs for pushing to PR
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    # only way of getting proper handling of glob paths
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $RULES_CHANGES_PATH
    - when: manual
      allow_failure: true

.ansible-rules:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "ansible/**"

# overrides of rulesset on a service by service basis
.docs-rules:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "docs/**"

.robot-service-tmplate-rules:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "RobotServiceTemplate/**"

# uses gitlab template without importing
.secret-scan-rules:
  stage: scan
  image: "$SECURE_ANALYZERS_PREFIX/secrets:$SECRETS_ANALYZER_VERSION$SECRET_DETECTION_IMAGE_SUFFIX"
  services: []
  allow_failure: false
  variables:
    GIT_DEPTH: "50"
  # `rules` must be overridden explicitly by each child job
  # see https://gitlab.com/gitlab-org/gitlab/-/issues/218444
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json

.web-service-template-rules:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "WebServiceTemplate/**"

jobs:
  flag-leaked-secrets:
    tags:
      - docker
    extends: .secret-scan-rules
    rules:
      - if: $CI_COMMIT_BRANCH
    script:
      - /analyzer run

  build-docs:
    extends: .docs-rules
    stage: build
    trigger:
      include: "docs/.docs-ci.yml"

  build-ansible:
    stage: build
    trigger:
      include: "ansible/.ansible-ci.yml"

  build-robot-service-template:
    stage: build
    trigger:
      include: "robot-service-tmplate-rules/.robot-service-ci.yml"

  build-web-service-template:
    stage: build
    trigger:
      include: "web-service-template-rules/.web-service-ci.yml"
