stages:
  - scan
  - build

# base pipe triggers on every change everywhere
# We to override this on a case by case basis
variables:
  RULES_CHANGES_PATH: "**/*"

  SECURE_ANALYZERS_PREFIX: "$CI_TEMPLATE_REGISTRY_HOST/security-products"
  SECRET_DETECTION_IMAGE_SUFFIX: ""

  SECRETS_ANALYZER_VERSION: "5"
  SECRET_DETECTION_EXCLUDED_PATHS: ""

.base-rules:
  rules:
    # always run for main
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    # avoid creation of duplicate jobs for pushing to PR
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    # only way of getting proper handling of glob paths
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $RULES_CHANGES_PATH
    - when: manual
      allow_failure: true

# uses gitlab template without importing
.secret-analyzer:
  stage: scan
  image: "$SECURE_ANALYZERS_PREFIX/secrets:$SECRETS_ANALYZER_VERSION$SECRET_DETECTION_IMAGE_SUFFIX"
  services: []
  allow_failure: false
  variables:
    GIT_DEPTH: "50"
  # `rules` must be overridden explicitly by each child job
  # see https://gitlab.com/gitlab-org/gitlab/-/issues/218444
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json

.docs-cicd-rules:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "docs/**"

.infra-cicd-rules:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "infra/**"

.cloud-cicd-rules:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "cloud/**"

.robot-cicd-rules:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "robot/**"

flag-leaked-secrets:
  extends: .secret-analyzer
  rules:
    - if: $SECRET_DETECTION_DISABLED == 'true' || $SECRET_DETECTION_DISABLED == '1'
      when: never
    - if: $CI_COMMIT_BRANCH
  script:
    - /analyzer run

docs-cicd:
  extends: .docs-cicd-rules
  stage: build
  needs: ["secret-scan"]
  trigger:
    include: "docs/.docs-ci.yml"

infra-cicd:
  stage: build
  needs: ["secret-scan"]
  trigger:
    include: "infra/.infra-ci.yml"

robot-cicd:
  stage: build
  needs: ["secret-scan"]
  trigger:
    include: "robot/.robot-ci.yml"

cloud-cicd:
  stage: build
  needs: ["secret-scan"]
  trigger:
    include: "cloud/.cloud-ci.yml"
