stages:
  - scan
  - trigger

variables:
  SECURE_ANALYZERS_PREFIX: "$CI_TEMPLATE_REGISTRY_HOST/security-products"
  SECRET_DETECTION_IMAGE_SUFFIX: ""
  SECRETS_ANALYZER_VERSION: "5"
  SECRET_DETECTION_EXCLUDED_PATHS: ""

  SERVICE_NAME: ""
  SERVICE_DIRECTORY: ""
  SERVICE_TAG_PREFIX: ""

# base job to be extended by downstream pipelines
.base-job:
  needs: ["flag-leaked-secrets"]
  stage: trigger
  rules:
    # triggers a downstream pipeline if >=1 conditions are met of::
    #
    #   1. A new tag is created
    #   2. A merge request is made with changes for a service
    #   3. A push to main is made with changes for a service
    #
    - if: "$CI_COMMIT_TAG =~ '$SERVICE_TAG_PREFIX-v*'"
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
      changes:
        - "$SERVICE_DIRECTORY/**"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - "$SERVICE_DIRECTORY/**"

  script:
    - echo "service CI/CD pipeline triggered"
    - echo SERVICE_NAME=$SERVICE_NAME
    - echo SERVICE_DIRECTORY=$SERVICE_DIRECTORY
    - echo SERVICE_TAG_PREFIX=$SERVICE_TAG_PREFIX

  trigger:
    include:
      - local: "$SERVICE_DIRECTORY/.*-ci.yml"

flag-leaked-secrets:
  stage: scan
  image: "$SECURE_ANALYZERS_PREFIX/secrets:$SECRETS_ANALYZER_VERSION$SECRET_DETECTION_IMAGE_SUFFIX"
  services: []
  allow_failure: false
  variables:
    GIT_DEPTH: "50"
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH
  script:
    - /analyzer run

docs:
  variables:
    SERVICE_NAME: "docs"
  extends: .base-job

ansible:
  variables:
    SERVICE_NAME: "ansible"
  extends: .base-job

robot-service-template:
  variables:
    SERVICE_NAME: "robot-service-template"
  extends: .base-job

web-service-template:
  variables:
    SERVICE_NAME: "web-service-template"
  extends: .base-job

robot-perception-service:
  variables:
    SERVICE_NAME: "perception"
  extends: .base-job
