stages:
  - "test"
  - "trigger"

include:
  - component: "templates/trigger"
    inputs:
      service_name: "docs"
      service_root: "docs"
  - component: "templates/trigger"
    inputs:
      service_name: "ansible"
      service_root: "ansible"
  - component: "templates/trigger"
    inputs:
      service_name: "web-service-template"
      service_root: "web-service-template"
  - component: "templates/trigger"
    inputs:
      service_name: "robot-service-template"
      service_root: "robot-service-template"
  - component: "templates/trigger"
    inputs:
      service_name: "robot-perception-service"
      service_root: "robot-perception-service"
