stages:
  - scan
  - info
  - trigger

variables:
  SECURE_ANALYZERS_PREFIX: "$CI_TEMPLATE_REGISTRY_HOST/security-products"
  SECRET_DETECTION_IMAGE_SUFFIX: ""
  SECRETS_ANALYZER_VERSION: "5"
  SECRET_DETECTION_EXCLUDED_PATHS: ""

  # overrides for downstream child services
  SERVICE_NAME: "" # name of service
  SERVICE_DIRECTORY: "" # root of project directory for service
  SERVICE_RELEASE_TAG_PATTERN: "" # valid regex pattern matching image tags

# base job to be extended by downstream pipelines
.base:
  rules:
    # trigger if changes are found in child directory
    - changes:
        - "$SERVICE_DIRECTORY/**/*"
    # trigger for any new tag matching service defined release pattern
    - if: "$CI_COMMIT_TAG =~ $SERVICE_RELEASE_TAG_PATTERN"

  needs: ["flag-leaked-secrets", "info"]
  stage: trigger
  trigger:
    include: "$SERVICE_DIRECTORY/.*-ci.yml"

flag-leaked-secrets:
  stage: scan
  image: "$SECURE_ANALYZERS_PREFIX/secrets:$SECRETS_ANALYZER_VERSION$SECRET_DETECTION_IMAGE_SUFFIX"
  services: []
  allow_failure: false
  variables:
    GIT_DEPTH: "50"
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json
  tags:
    - docker
  script:
    - /analyzer run

info:
  stage: info
  tags: ["docker-build"]
  script:
    - "echo Starting jobs for SERVICE=$SERVICE_NAME"
    - "echo Reacting to changes in $SERVICE_DIRECTORY"
    - "echo Releasing all tags matching pattern: $SERVICE_RELEASE_TAG_PATTERN"

docs:
  variables:
    SERVICE_NAME: "docs"
    SERVICE_DIRECTORY: $SERVICE_NAME

    # NOTE: don't try to variables like $SERVICE_NAME directly in pattern.
    SERVICE_RELEASE_TAG_PATTERN: '/^docs-v(\d+.){1,2}\d+$/'

  extends: .base

ansible:
  variables:
    SERVICE_NAME: "ansible"
    SERVICE_DIRECTORY: $SERVICE_NAME

    # NOTE: don't try to variables like $SERVICE_NAME directly in pattern.
    SERVICE_RELEASE_TAG_PATTERN: '/^ansible-v(\d+.){1,2}\d+$/'

  extends: .base

robot-service-template:
  variables:
    SERVICE_NAME: "robot-service-template"
    SERVICE_DIRECTORY: $SERVICE_NAME
    SERVICE_TAG_PREFIX: $SERVICE_NAME

    # NOTE: don't try to variables like $SERVICE_NAME directly in pattern.
    SERVICE_RELEASE_TAG_PATTERN: '/^robot-service-template-v(\d+.){1,2}\d+$/'

  extends: .base

web-service-template:
  variables:
    SERVICE_NAME: "web-service-template"
    SERVICE_DIRECTORY: SERVICE_NAME
    SERVICE_TAG_PREFIX: $SERVICE_NAME

    # NOTE: don't try to variables $SERVICE_NAME directly in pattern.
    SERVICE_RELEASE_TAG_PATTERN: '/^web-service-template-v(\d+.){1,2}\d+$/'

  extends: .base

robot-perception-service:
  variables:
    SERVICE_NAME: "perception"
    SERVICE_DIRECTORY: "perception"

    # NOTE: don't try to variables $SERVICE_NAME directly in pattern.
    SERVICE_RELEASE_TAG_PATTERN: '/^robot-perception-service-v(\d+.){1,2}\d+$/'

  extends: .base
