image: docker

services:
  - docker:dind

default:
  tags: ["docker-build"]

workflow:
  auto_cancel:
    on_job_failure: all

stages:
  - scan
  - trigger

before_script:
  - printenv

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml

  - local: "templates/trigger.yml"
    inputs:
      service: "robot-perception-service"
      
  - local: "templates/trigger.yml"
    inputs:
      service: "robot-papper-perception-service"          
      
  - local: "templates/trigger.yml"
    inputs:
      service: "robot-steering-service"

  - local: "templates/trigger.yml"
    inputs:
      service: "robot-service-template"

  - local: "templates/trigger.yml"
    inputs:
      service: "cloud-service-template"

# override secret detection so stage is "scan"
secret_detection:
  stage: scan
  tags:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"
  allow_failure: false
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json
    # this is the way to make artifacts appear
    paths:
      - gl-secret-detection-report.json
    expire_in: 1 day
