# similar to project level delegation but actually delegates
# to actual service CICD pipes that builds things.

stages:
  - build

variables:
  RULES_CHANGES_PATH: "robot/**"

# cannot conflict with already defined base_rules
.robot_base_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $RULES_CHANGES_PATH

.robot-service-template:
  extends: .robot_base_rules
  variables:
    RULES_CHANGES_PATH: "robot/cpp-robot-service-template/**"

robot-service-template:
  stage: build
  needs: []
  trigger:
    include: "robot/cpp-robot-service-template/robot-ci.yml"
