# delegates to child .yml specified ci jobs for each service
before_scipt:
  - cd robot

stages:
  - service-triggers

- cpp-robot-service-trigger:
  stage: service-triggers 
  trigger:
    include: cpp-robot-service-template/cpp-robot-service-ci.yml
  rules:
    - changes:
        - cpp-robot-service-template/*

