# similar to project level delegation but actually delegates 
# to actual service CICD pipes that builds things.

.cpp-robot-service-template
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "robots/cpp-robot-service-template/**"

cicd-cpp-robot-service-template:
  stage: build
  needs: []
  include:
    - local: robot/cpp-robot-service-template/.robot-service-ci.yml

