image: docker

variables:
  RELEASE_TAG_PATTERN: '/^$SERVICE_TAG_PREFIX-v(\d+.){1,2}\d+$/'

services:
  - name: docker:dind

stages:
  - info
  - build
  - release

before_script:
  - "cd $SERVICE_DIRECTORY"
  - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"

info:
  tags: ["docker-build"]
  stage: info
  script:
    - "echo Starting jobs for SERVICE=$SERVICE_NAME"
    - "echo Reacting to changes in $SERVICE_DIRECTORY"
    - "echo Releasing all versioned tags matching prefix: $SERVICE_TAG_PREFIX"

build:
  tags: ["docker-build"]
  needs: ["info"]
  stage: build
  script:
    - "echo 'building web service...'"

release:
  tags: ["docker-build"]
  needs: ["build"]
  stage: release
  script:
    - "echo 'releasing web service...'"
  rules:
    - if: $CI_COMMIT_TAG =~ $RELEASE_TAG_PATTERN
