before_script:
  - cd cloud

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - echo "building"

unit-tests:
  stage: test
  script:
    - echo "Running unit tests"

e2e-tests:
  stage: test
  script:
    - echo "Running E2E tests"

push:
  stage: release
  script:
    - echo "pushing image to registry"
