team11:
  vars:
    tailscale:
      auth_token: "tskey-auth-kXdsQDr95921CNTRL-gpV35r9oSrLapPWivreskLzePvgUUcof"

    grafana:
      user: team11
      password: team11
      password_hash: "$2a$14$1l.IozJx7xQRVmlkEQ32OeEEfP5mRxTpbDTCTcXRqn19gXD8YK1pO"

    gitlab:
      uri: git.chalmers.se/erhaka/team11-project-monorepo.git
      user: robot
      token: glpat-qNukPk-czxCrpzfdAgMx
      project: team11-project-monorepo

  hosts:
    cloud:
      ansible_host: 100.126.124.31
      ansible_user: pi
