Vagrant.configure("2") do |config| 
    config.vm.box = "debian/buster64" 
    
    config.vm.hostname = "team11-server"
    config.ssh.username = "pi"
    
    config.vm.provider "virtualbox" do |vb| 
        vb.memory = "4024" 
        vb.cpus = "1" 
    end    
    
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    config.ssh.forward_agent = true
    config.ssh.keys_only = false

    # Disables the vagrant generated key.
    # Uncomment if you only want access via user's key.
    config.ssh.insert_key = false
      config.vm.provision "ansible" do |ansible|
          ansible.verbose = "v"        
          ansible.playbook = "bootstrap.yml"
      end
end
