image: docker

services:
  - name: docker:dind

stages:
  - build
  - release

build:
  tags: ["docker-build"]
  stage: build
  script:
    - docker build .

include:
  - local: "templates/release.yml"
    inputs:
      service_name: "robot-service-template"
      service_root: "robot-service-template"
      platforms: "linux/amd64,linux/arm64,linux/arm/v7"
