# component-ish template for cloud services
spec:
  inputs:
    service:
---
image: docker

services:
  - docker:dind

default:
  tags: ["docker-build"]

stages:
  - lint
  - build
  - test
  - release

"lint-$[[ inputs.service ]]":
  stage: lint
  script:
    - "echo 'running linter...'"

"build-$[[ inputs.service ]]":
  stage: build
  script:
    - "docker build ."

"unit-test-$[[ inputs.service ]]":
  stage: test
  script:
    - "echo 'building $service'"

"e2e-test-$[[ inputs.service ]]":
  stage: test
  script:
    - "echo 'running unit tests...'"

"release-$[[ inputs.service ]]":
  variables:
    RELEASE_TAG_PATTERN: "/^$[[ inputs.service ]]-$VERSION_PATTERN$$/"
  rules:
    - if: "$CI_COMMIT_TAG != null && $CI_BUILD_TAG =~ $RELEASE_TAG_PATTERN"
    - if: "$CI_COMMIT_BRANCH != null && $CI_COMMIT_BRANCH =~ $RELEASE_TAG_PATTERN"
  stage: release
  script:
    - cd "$[[ inputs.service ]]"
    - docker build -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" --push .
