before_script:
  - cd ansible

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

stages:
  - lint
  - test
  - release

build:
  stage: lint
  script:
    - echo "linting playbooks"

test:
  stage: test
  script:
    - echo "Running unit tests for all playbooks"

release:
  stage: release
  script:
    - echo "Rreleasing new playbooks"
