image: docker

services:
  - name: docker:dind

stages:
  - lint
  - build
  - test
  - release

before_script:
  - cd $SERVICE_ROOT

lint:
  tags: ["docker-build"]
  stage: lint
  script:
    - "echo 'running linter...'"

build:
  tags: ["docker-build"]
  stage: build
  script:
    - "echo 'building $SERVICE_NAME'"

unit-test:
  tags: ["docker-build"]
  stage: test
  script:
    - "echo 'running unit tests..."

e2e-test:
  tags: ["docker-build"]
  stage: test
  script:
    - "echo 'running unit tests..."

release:
  stage: release
  tags: ["docker-build"]
  rules:
    - if: "$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $RELEASE_TAG_PATTERN"
  script:
    - "echo 'releasing $SERVICE_NAME'"
