image: docker

services:
  - name: docker:dind

before_script:
  - cd robot-service-template
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - release

build-amd64:
  tags: ["docker-build"]
  stage: build
  script:
    - docker build .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

push:
  tags: ["docker-build"]
  stage: release
  script:
    - docker run --privileged --rm tonistiigi/binfmt --install all
    - docker buildx create --name multiplatformbuilder --use
    - docker buildx build --platform "$PLATFORMS" -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" --push .
  rules:
    # note that the name of the service needs to be prepended to release tags!
    # Gitlab does not support interpolation inside of regex strings.
    - if: $CI_COMMIT_TAG =~ /^robot-service-template-(\d+\.\d+\.\d+)$/
