before_script:
  - cd docs

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - echo "building docs!"

unit-tests:
  stage: test
  script:
    - echo "This job runs unit tests."

e2e-tests:
  stage: test
  script:
    - echo "This job runs E2E tests."

release:
  stage: release
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
