image: docker

services:
  - name: docker:dind

stages:
  - build
  - release

before_script:
  - printenv
  - cd docs

build:
  stage: build
  script:
    - "echo 'building docs...'"

release:
  stage: release
  script:
    - "echo 'publishing docs...'"
  rules:
    - if: "($CI_COMMIT_TAG != null && $CI_COMMIT_TAG =~ $RELEASE_TAG_PATTERN)"
