image: docker

services:
  - name: docker:dind

stages:
  - build
  - release

.base:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

before_script:
  - "cd $SERVICE_DIRECTORY"

build:
  extends: .base
  stage: build
  script:
    - "echo 'building docs...'"

release:
  extends: .base
  stage: release
  script:
    - "echo 'publishing docs...'"
  rules:
    - if: $CI_COMMIT_TAG =~ $SERVICE_RELEASE_TAG_PATTERN
